name: "Building release binaries on Windows"

on: [push]

jobs:
  Windows-Build:

    runs-on: windows-latest
    env:
      LIB_VERSION: 2.2.0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: install yubihsm-shell
        run: |
          $ErrorActionPreference = "Stop"
          Set-PSDebug -Trace 1

          cd ..
          Invoke-WebRequest -Uri https://developers.yubico.com/yubihsm-shell/Releases/yubihsm-shell-$env:LIB_VERSION.tar.gz -OutFile yubihsm-shell.tar.gz -UseBasicParsing
          tar xf yubihsm-shell.tar.gz

          ls
          ls yubihsm-shell-$env:LIB_VERSION

          C:/vcpkg/vcpkg.exe install openssl:x64-windows
          $env:OPENSSL_ROOT_DIR ="C:/vcpkg/packages/openssl_x64-windows"
          cd yubihsm-shell-$env:LIB_VERSION
          mkdir build; cd build
          cmake -A x64 -DBUILD_ONLY_LIB=ON ..
          cmake --build .
          ls lib
          ls lib/Debug

      - name: clone yubihsmrs
        run: |
          $ErrorActionPreference = "Stop"
          Set-PSDebug -Trace 1

          pwd

          cd ..
          git clone https://github.com/Yubico/yubihsmrs.git
          ls
          ls yubihsm-setup

      - name: Build yubihsm-setup
        run: |
          $ErrorActionPreference = "Stop"
          Set-PSDebug -Trace 1
          mkdir artifact

          rustc.exe RUST_BACKTRACE=1 YUBIHSM_LIB_DIR=$env:GITHUB_WORKSPACE/../yubihsm-shell-$env:LIB_VERSION/build/lib/Debug cargo.exe build --release
          install target/release/yubihsm-setup $env:GITHUB_WORKSPACE/artifact/yubihsm-setup

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: yubihsm-setup
          path: artifact
