name: "Building release binaries on Windows"

on: [push]

jobs:
  Windows-Build:

    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: clone yubihsmrs
        run: |
          $ErrorActionPreference = "Stop"
          Set-PSDebug -Trace 1
          mkdir artifact

          pwd

          cd ..
          git clone https://github.com/Yubico/yubihsmrs.git

          ls
          ls yubihsm-setup

      - name: install yubihsm-shell
        run: |
          $ErrorActionPreference = "Stop"
          Set-PSDebug -Trace 1

          cd ..
          Invoke-WebRequest -Uri  https://developers.yubico.com/YubiHSM2/Releases/yubihsm2-sdk-2021-04-windows-amd64.zip -OutFile yubihsm2-sdk-2021-04-windows-amd64.zip -UseBasicParsing
          Add-Type -AssemblyName System.IO.Compression.FileSystem
          [System.IO.Compression.ZipFile]::ExtractToDirectory("$env:GITHUB_WORKSPACE/../yubihsm2-sdk-2021-04-windows-amd64.zip", "$env:GITHUB_WORKSPACE/../yubihsm2-sdk")

          ls
          ls yubihsm2-sdk/yubihsm2-sdk/

          mkdir yubihsm-shell
          msiexec /i "D:\a\yubihsm-setup\yubihsm2-sdk\yubihsm2-sdk\yubihsm-shell-x64.msi" INSTALLDIR="$env:GITHUB_WORKSPACE/../yubihsm-shell" /q
          Get-Childitem –Path D:\ -Include "yubihsm-shell.exe" -Recurse -ErrorAction SilentlyContinue
          
