name: "Building release binaries on Windows"

on: [push]

jobs:
  Windows-Build:

    runs-on: windows-latest
    env:
      LIB_VERSION: 2.2.0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: clone yubihsmrs
        run: |
          $ErrorActionPreference = "Stop"
          Set-PSDebug -Trace 1
          mkdir artifact

          pwd

          cd ..
          git clone https://github.com/Yubico/yubihsmrs.git

          ls
          ls yubihsm-setup

      - name: install yubihsm-shell
        run: |
          $ErrorActionPreference = "Stop"
          Set-PSDebug -Trace 1

          Get-Childitem –Path C:\ -Include libcrypto*.dll -Recurse -ErrorAction SilentlyContinue